source: .
destination: ./_site
includes: ./_includes
baseurl: ""
url: "https://raswanthprasath.com"
relative_url: "https://raswanthprasath.com"
permalink: /:year/:month/:day/:title
title: "Raswanth Prasath"
description: "Raswanth Prasath - Personal Website"

markdown: kramdown
highlighter: none
kramdown:
  input: GFM

feed:
  excerpt_only: true
  posts_limit: 15

picture:
  ignore_missing_images: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
